/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.*;

import java.io.*;

public class AppTest {
    @Test
    void testQuoteConstructor() throws FileNotFoundException {
        String testResponse = App.findRandomQuote("src/main/resources/recentquotes.json");
//        boolean test = testResponse != null;
//        Assert.assertTrue("find random quote returns quote", test);
    }
}
