/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.*;

import java.io.*;

public class AppTest {
    @Test
    public void testApp(){
        File testFile = new File("src/main/resources/recentquotes.json");
        boolean test = testFile.exists();
        Assert.assertTrue("File should exist",test);
    }
    @Test
    public void testRonSwansonIfYouDare() throws IOException {
        String expected = "Ron Swanson";
        Assert.assertEquals("Author should be Ron Swanson",expected,App.getRonSwanson().author);
    }
}
