/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Random;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        findRandomQuote("src/main/resources/recentquotes.json");
    }
    public static String findRandomQuote(String path) throws FileNotFoundException {
        Gson gson = new Gson();
        FileReader reader = new FileReader(path);

        Quote[] quotey = gson.fromJson(reader,Quote[].class);

        Random rand = new Random();
        int random = rand.nextInt(quotey.length);
        return quotey[random].toString();
    }
}
